### ISSUE TITLE
Minor issue:  regarding game-over state

### ISSUE THREAD

**Issue by sashabjorkman** [INDA23PlusPlus/emilaa-chess#2]
The following position incorrectly marks the game as ended:
![image](https://github.com/INDA23PlusPlus/emilaa-chess/assets/97904317/01a111d5-2914-4e5b-aad0-1a7abeaaad27)
This is no major issue as the functionality of the GUI can still be demonstrated using other positions. If the fix is immediately clear then I suppose fixing it could be worth it.

**Comment by emilaalto** [comment]
I won't fix it for todays lesson, but I'll look into it. 👍

**Comment by emilaalto** [comment]
I think it's fixed. :+1:
